Added thread.currentid()
madmaxoft/LuaMultiThreaded2 pull request #1
Opened 2022-09-30 12:33 UTC by NiLSPACE

Makes it easier to debug the Lua code to identify which thread is running

2022-09-30 12:46 UTC, madmaxoft requested changes
I think the code pushing the thread ID onto Lua stack should be hoisted to a separate function.

2022-09-30 12:53 UTC, madmaxoft commented
Also, ideally you should add a script into /tests that tests / shows the functionality.

2022-09-30 14:08 UTC, madmaxoft requested changes

2022-09-30 14:08 UTC, madmaxoft commented on src/Utils.h
> +int pushThreadIdOnLuaStack(lua_State* aState, std::thread::id aThreadId);
```suggestion
int pushThreadIdOnLuaStack(lua_State * aState, const std::thread::id & aThreadId);
```

2022-09-30 14:08 UTC, madmaxoft commented on tests/CurrentThreadId.lua
> +-- The extra second is to give the main thread more time to retrieve the id.
One second may be too much, `0.1` should be enough.

We'll get rid of this anyway, when we add mutexes / condvars / semaphores

2022-09-30 14:08 UTC, madmaxoft commented on tests/CurrentThreadId.lua
> +-- Variable which the sub thread will save it's id in.
```suggestion
-- Variable which the sub thread will save its id in.
```

2022-09-30 14:24 UTC, NiLSPACE commented
That should do it :)

2022-10-01 20:01 UTC, madmaxoft approved these changes

2022-10-01 20:02 UTC, merged